[package]
name = "plonky2-aes"
version = "0.1.0"
edition = "2024"

[dependencies]
plonky2 = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
rand = "0.10.0"
aes = "0.8.4"
aes-gcm = "0.10.3"
hex = "0.4.3"
