[package]
name = "plonky2-aes"
version = "0.1.0"
edition = "2024"

[dependencies]
plonky2 = { git = "https://github.com/0xPARC/plonky2.git", rev = "109d517d09c210ae4c2cee381d3e3fbc04aa3812" }
anyhow = "1.0.56"

[dev-dependencies]
rand = "0.10.0"
aes = "0.8.4"
aes-gcm = "0.10.3"
hex = "0.4.3"
